repo_server: updated scripts

diff --git a/roles/repo_server/templates/1_sync_repo_to_new_version.sh.j2 b/roles/repo_server/templates/1_sync_repo_to_new_version.sh.j2
--- a/roles/repo_server/templates/1_sync_repo_to_new_version.sh.j2
+++ b/roles/repo_server/templates/1_sync_repo_to_new_version.sh.j2
@@ -5,7 +5,6 @@ set -ueo pipefail
 _main="{{ main_repo_path }}"
 
 {% raw %}
-
 ! test -d "${_main}/0cache" && mkdir "${_main}/0cache"
 
 print_all_repos() {
@@ -35,16 +34,19 @@ if [[ -z "${_do_repos:-}" ]]; then
 fi
 
 for _repo in ${_do_repos}; do
+   echo ""
    _repo_log_dir="${_main}/reposync.logs/${_os_distribution}/${_repo}"
    ! test -d "${_repo_log_dir}" && mkdir -p "${_repo_log_dir}"
    _repo_log="${_repo_log_dir}/${_time}"
-   echo "Log file: ${_repo_log}"
-   dnf reposync --conf "${_main}/dnf.repos.d/${_os_distribution}.conf" --repo "${_repo}" --downloaddir="${_main}/0cache/${_os_distribution}/" 1>"${_repo_log}" 2>&1 && \
-   mkdir -p "${_main}/1versions/${_os_distribution}/${_repo}/" && \
+   echo "  Log file: ${_repo_log}"
+   if ! dnf reposync --conf "${_main}/dnf.repos.d/${_os_distribution}.conf" --repo "${_repo}" --downloaddir="${_main}/0cache/${_os_distribution}/" 1>"${_repo_log}" 2>&1; then
+      echo "Error, unsuccessfull"
+      continue
+   fi
+   mkdir -p "${_main}/1versions/${_os_distribution}/${_repo}/"
    cp -a --reflink=always "${_main}/0cache/${_os_distribution}/${_repo}/" "${_main}/1versions/${_os_distribution}/${_repo}/${_time}/" || exit
    echo "New version created:   ${_main}/1versions/${_os_distribution}/${_repo}/${_time}"
-   echo ""
-   echo ""
 done
 
+echo "done"
 {% endraw %}
diff --git a/roles/repo_server/templates/2_new_repo_distribution.sh.j2 b/roles/repo_server/templates/2_new_repo_distribution.sh.j2
--- a/roles/repo_server/templates/2_new_repo_distribution.sh.j2
+++ b/roles/repo_server/templates/2_new_repo_distribution.sh.j2
@@ -4,26 +4,29 @@
 set -ueo pipefail
 
 _main="{{ main_repo_path }}"
+cd ${_main}
 
 {% raw %}
 _prompt=false
-OPTSTRING=":s:d:r:v:p"
+OPTSTRING=":s:c:d:r:v:p"
 while getopts ${OPTSTRING} opt; do
   case ${opt} in
-    s) _stack=${OPTARG} && echo "_stack=${_stack}" ;;
-    d) _distroselect=${OPTARG} && echo "_distroselect=${_distroselect}" ;;
-    r) _repoarg=${OPTARG} && echo "_repoarg=${_repoarg}" ;;
-    v) _versionarg=${OPTARG} && echo "_versionarg=${_versionarg}" ;;
+    s) _stack=${OPTARG} && echo "this stack: ${_stack}" ;;
+    c) _copy=${OPTARG} && echo "copy from: ${_copy}" ;;
+    d) _distroarg=${OPTARG} && echo "distribution: ${_distroarg}" ;;
+    r) _repoarg=${OPTARG} && echo "repository: ${_repoarg}" ;;
+    v) _versionarg=${OPTARG} && echo "version: ${_versionarg}" ;;
     p) _prompt=true ;;
     *)
        echo "Error, at least [stack_prefix] is missing. Use"
-       echo "  ${0} -s stack [-o string] [-r string|ALL] [-v string] [-p]"
+       echo "  ${0} [-c stack] -s stack [-o string] [-r string|ALL] [-v string] [-p]"
        echo " where"
        echo "   -s string       is a name of the stack abbrevation, e.g. 'nb'"
        echo "   -d string       is distribution, e.g. 'rocky9'"
        echo "   -r string|ALL   is name of specific repository, e.g. 'ryslog7' or 'ALL' for all repositories"
        echo "   -v string       in case of specific repository, this is a specific version to be used for a stack"
        echo "                   Note: if no version is selected, then the last one will be used!"
+       echo "   -c string       copy from this stack settings, e.g. '-c hc -s nb' would copy from hc to nb"
        echo ""
        cd ${_main}/2deploy/
        echo "Available stacks are: "
@@ -37,21 +40,35 @@ done
 if [[ -z "${_stack:-}" ]]; then
    echo "Stack missing, exiting ..." && exit 1
 fi
-if [[ -n "${_distroselect:-}" ]]; then
-   ! test -d "${_main}/1versions/${_distroselect}" && echo "Error, wrong distribution" && exit
-   if [[ -z "${_repoarg:-}" || -z "${_stack:-}" ]]; then
+
+if [[ -n "${_stack:-}" && -n "${_copy:-}" ]]; then
+   if test -d "2deploy/${_copy}"; then
+      test -d "2deploy/${_stack}" && rm -rf 2deploy/${_stack:-error}
+      cp -rf "2deploy/${_copy}" "2deploy/${_stack}"
+      echo "Done - stack copied"
+      exit 0
+   else
+      echo "Stack ${_copy} does not exist, cannot copy from ... exiting"
+      exit 1
+   fi
+fi
+
+if [[ -n "${_distroarg:-}" ]]; then
+   ! test -d "${_main}/1versions/${_distroarg}" && echo "Error, wrong distribution" && exit
+   if [[ -z "${_repoarg:-}" || -z "${_stack:-}" ]] && [[ ! ${_prompt} ]]; then
       echo "Stack or repository missing" && exit 1
    fi
 fi
+
 if [[ -n "${_repoarg:-}" ]]; then
-   if [[ -z "${_distroselect:-}" || -z "${_stack:-}" ]]; then
+   if [[ -z "${_distroarg:-}" || -z "${_stack:-}" ]]; then
       echo "Stack or distribution missing" && exit 1
    fi
    if [[ "${_repoarg:-}" == "ALL" ]]; then
-      _reposelect="$(find ${_main}/1versions/${_distroselect}/ -mindepth 1 -maxdepth 1 -type d -printf ' %P\n' 2>/dev/null)" || \
-      { echo "Error, could not find versions in the ${_main}/1versions/${_distroselect}"; exit; }
+      _reposelect="$(find ${_main}/1versions/${_distroarg}/ -mindepth 1 -maxdepth 1 -type d -printf ' %P\n' 2>/dev/null)" || \
+      { echo "Error, could not find versions in the ${_main}/1versions/${_distroarg}"; exit; }
    else # check that selected repository exists
-      if ! test -d "${_main}/1versions/${_distroselect}/${_repoarg}"; then
+      if ! test -d "${_main}/1versions/${_distroarg}/${_repoarg}"; then
          echo "Error, repository does not exist for this distribution"
          exit
       else
@@ -59,8 +76,9 @@ if [[ -n "${_repoarg:-}" ]]; then
       fi
    fi
 fi
+
 if [[ -n "${_versionselarg:-}" ]]; then
-   if [[ -z "${_stack:-}" || -z "${_distroselect:-}" || -z "${_reposelect:-}" ]]; then
+   if [[ -z "${_stack:-}" || -z "${_distroarg:-}" || -z "${_reposelect:-}" ]]; then
       echo "Stack, distribution or repository missing" && exit 1
    fi
 fi
@@ -83,54 +101,56 @@ if ! test -d ${_main}/2deploy/${_stack}; then
    echo ""
 fi
 
-for _each_repo in ${_reposelect}; do
-   if "${_prompt}"; then
-      echo "________ OS distributions available __________"
-      _distroselect="error"
-      while true; do
-         test -d "${_main}/1versions/${_distroselect}" 2>/dev/null && break
-         find "${_main}/1versions/" -mindepth 1 -maxdepth 1 -type d -printf '    %P\n'
-         read -p "> select: " _distroselect
-         echo ""
-         echo "  You picked:   ${_distroselect}"
-         test -d "${_main}/1versions/${_distroselect}" || echo "Wrong distribution, try again!"
-      done
+if "${_prompt}"; then
+   echo "________ OS distributions available __________"
+   _distroselect="${_distroarg:-error}"
+   while true; do
+      test -d "${_main}/1versions/${_distroselect}" 2>/dev/null && break
+      find "${_main}/1versions/" -mindepth 1 -maxdepth 1 -type d -printf '    %P\n'
+      read -p "> select: " _distroselect
+      echo ""
+      echo "  You picked:   ${_distroselect}"
+      test -d "${_main}/1versions/${_distroselect}" || echo "Wrong distribution, try again!"
+   done
 
-      echo "________ Select repository from the ${_distroselect} __________"
-      _reposelect="error"
-      while true ; do
-         test -d "${_main}/1versions/${_distroselect}/${_reposelect}" 2>/dev/null && break
-         find "${_main}/1versions/${_distroselect}" -mindepth 1 -maxdepth 1 -type d -printf '    %P\n'
-         read -p "> select: " _reposelect
-         echo "  You picked:   ${_reposelect}"
-         test -d "${_main}/1versions/${_distroselect}/${_reposelect}" || echo "Wrong repository, try again!"
-         echo ""
-      done
+   echo "________ Select repository from the ${_distroselect} __________"
+   _reposelect="${_repoarg:-error}"
+   while true ; do
+      test -d "${_main}/1versions/${_distroselect}/${_reposelect}" 2>/dev/null && break
+      find "${_main}/1versions/${_distroselect}" -mindepth 1 -maxdepth 1 -type d -printf '    %P\n'
+      read -p "> select: " _reposelect
+      echo "  You picked:   ${_reposelect}"
+      test -d "${_main}/1versions/${_distroselect}/${_reposelect}" || echo "Wrong repository, try again!"
+      echo ""
+   done
 
-      echo "________ Select versions from the ${_distroselect}/${_reposelect} ____________"
-      _versionselect="error"
-      while true; do
-         test -d "${_versionselect}" 2>/dev/null && break
-         find "${_main}/1versions/${_distroselect}/${_reposelect}" -mindepth 1 -maxdepth 1 -type d -printf '    %P\n'
-         read -p "> select: " _versionselect
-         echo "  You picked:   ${_versionselect}"
-         test -d "${_main}/1versions/${_distroselect}/${_reposelect}/${_versionselect}" || echo "Wrong version, try again!"
-	 _versionselect="1versions/${_distroselect}/${_reposelect}/${_versionselect}"
-         echo ""
-      done
-   else # no prompt needed
-      cd "${_main}"
-      echo "test -d 1versions/${_distroselect}/${_each_repo}"
-      test -d "1versions/${_distroselect}/${_each_repo}" || { echo "Error, no repository found at 1versions/${_distroselect}/${_each_repo}"; exit; }
-      if [[ -z "${_versionarg:-}" ]]; then        # no version was PROVIDED, selecting LATEST version
-         _versionselect="$(find 1versions/${_distroselect}/${_each_repo} -maxdepth 1 -mindepth 1 -type d -printf '%T@ %p\n' | sort -nr | head -1 | cut -d' ' -f2-)" || \
-           { echo "Error finding latest version."; exit; }
-      fi
-      if [[ -z "${_versionselect:-}" ]]; then     # no version was FOUND
-         echo "No version was found in the 1versions/${_distroselect}/${_each_repo}."; exit;
-      else
-         echo "  picked version ${_versionselect}"
-      fi
+   echo "________ Select versions from the ${_distroselect}/${_reposelect} ____________"
+   _versionselect="error"
+   while true; do
+      test -d "${_versionselect}" 2>/dev/null && break
+      find "${_main}/1versions/${_distroselect}/${_reposelect}" -mindepth 1 -maxdepth 1 -type d -printf '    %P\n'
+      read -p "> select: " _versionselect
+      echo "  You picked:   ${_versionselect}"
+      test -d "${_main}/1versions/${_distroselect}/${_reposelect}/${_versionselect}" || echo "Wrong version, try again!"
+      _versionselect="1versions/${_distroselect}/${_reposelect}/${_versionselect}"
+      echo ""
+   done
+fi
+
+
+
+for _each_repo in ${_reposelect:-error}; do
+   cd "${_main}"
+   test -d "1versions/${_distroselect}/${_each_repo}" || { echo "Error, no repository found at 1versions/${_distroselect}/${_each_repo}"; exit; }
+   if [[ -z "${_versionarg:-}" ]]; then        # no version was PROVIDED, selecting LATEST version
+      _versionselect="$(find 1versions/${_distroselect}/${_each_repo} -maxdepth 1 -mindepth 1 -type d -printf '%T@ %p\n' | sort -nr | head -1 | cut -d' ' -f2-)" || \
+        { echo "Error finding latest version."; exit; }
+   fi
+
+   if [[ -z "${_versionselect:-}" ]]; then     # no version was FOUND
+      echo "No version was found in the 1versions/${_distroselect}/${_each_repo}."; exit;
+   else
+      echo "  picked version ${_versionselect}"
    fi
 
    if ! test -d "${_versionselect}"; then
@@ -143,9 +163,9 @@ for _each_repo in ${_reposelect}; do
          echo "   2deploy/${_stack}/${_each_repo}  ->  ${_versionselect}"
          read -p "> press [enter] to confirm"
       fi
-      echo ">>>>> ln -f -s "${_versionselect}" "2deploy/${_stack}/${_each_repo}""
+      ln -f -s "../../${_versionselect}" "2deploy/${_stack}/${_each_repo}"
       echo ""
    fi
 done
-
+echo "done"
 {% endraw %}
