deploy release manager (#3629)

diff --git a/roles/subgroup_directories/templates/release_manager.sh.j2 b/roles/subgroup_directories/templates/release_manager.sh.j2
--- a/roles/subgroup_directories/templates/release_manager.sh.j2
+++ b/roles/subgroup_directories/templates/release_manager.sh.j2
@@ -18,32 +18,44 @@ fi
 
 # Extract group name from username
 DM_GROUP="${BASH_REMATCH[1]}"
-
-########################################
-# CONFIG
-########################################
-
-lfs_tmp="{{ lfs_tmp }}"
-lfs_rsc="{{ lfs_rsc }}"
-
-BASE="/groups/L-${DM_GROUP}/tmp09"
-RELEASES="${BASE}/rel"
 GROUP="L-${DM_GROUP}-rel"
 
-# Check tmp location
-if [[ "${CURRENT_DIR}" == "/groups/L-${DM_GROUP}/tmp"* ]] && [[ -z "${lfs_tmp}" ]]; then
-    echo "[ERROR] lfs_tmp is empty, but release_manager.sh is being executed from a tmp location." >&2
-    echo "        Current location: ${CURRENT_DIR}" >&2
+#########################################
+# Set LFS_TMP, LFS_RSC BASED, RELEASE Dirs
+# based on current `pwd`.
+#########################################
+
+LFS_TMP="{{ lfs_mounts | selectattr('lfs', 'match', '^tmp[0-9]{2}$') | map(attribute='lfs') | first | default('') }}"
+LFS_RSC="{{ (lfs_mounts | selectattr('lfs', 'match', '^rsc([0-9]{2})$') | map(attribute='lfs') | first) | default('') }}"
+
+
+if [[ "${CURRENT_DIR}" == "/groups/L-${DM_GROUP}/tmp"* ]]; then
+
+    if [[ -z "${LFS_TMP}" ]]; then
+        echo "[ERROR] LFS_TMP is empty, but release_manager.sh is being executed from a tmp location." >&2
+        echo "        Current location: ${CURRENT_DIR}" >&2
+        exit 1
+    fi
+
+    BASE="/groups/L-${DM_GROUP}/${LFS_TMP}"
+
+elif [[ "${CURRENT_DIR}" == "/groups/L-${DM_GROUP}/rsc"* ]]; then
+
+    if [[ -z "${LFS_RSC}" ]]; then
+        echo "[ERROR] LFS_RSC is empty, but release_manager.sh is being executed from an rsc location." >&2
+        echo "        Current location: ${CURRENT_DIR}" >&2
+        exit 1
+    fi
+
+    BASE="/groups/L-${DM_GROUP}/${LFS_RSC}"
+
+else
+    echo "[ERROR] Unknown location: ${CURRENT_DIR}" >&2
     exit 1
 fi
 
-# Check rsc location
-if [[ "${CURRENT_DIR}" == "/groups/L-${DM_GROUP}/rsc"* ]] && [[ -z "${lfs_rsc}" ]]; then
-    echo "[ERROR] lfs_rsc is empty, release_manager.sh is being executed from an rsc location." >&2
-    echo "        Current location: ${CURRENT_DIR}" >&2
-    exit 1
-fi
 
+RELEASES="${BASE}/rel"
 
 ########################################
 # HELP
